//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfCafica.Contexts.Administracion
{
    using System;
    using System.Collections.Generic;
    
    public partial class BDEmpresas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BDEmpresas()
        {
            this.BDEmpresasRoles = new HashSet<BDEmpresasRoles>();
        }
    
        public long Id { get; set; }
        public string RazonSocial { get; set; }
        public string RFC { get; set; }
        public string Status { get; set; }
        public string SalidasSinExistencia { get; set; }
        public string MetodoCosteo { get; set; }
        public string ContrasenaReportes { get; set; }
        public string ValidaVariacionCosto { get; set; }
        public Nullable<double> PorcentajeVariacionCosto { get; set; }
        public Nullable<System.DateTime> InicioPeriodo { get; set; }
        public Nullable<System.DateTime> FinPeriodo { get; set; }
        public string UsuarioCreo { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModifico { get; set; }
        public Nullable<System.DateTime> FechaUltimaModificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BDEmpresasRoles> BDEmpresasRoles { get; set; }
    }
}
