//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfCafica.Contexts.Administracion
{
    using System;
    using System.Collections.Generic;
    
    public partial class t3
    {
        public long id { get; set; }
        public Nullable<long> t1id { get; set; }
        public Nullable<long> t2id { get; set; }
    
        public virtual t1 t1 { get; set; }
        public virtual t2 t2 { get; set; }
    }
}
