//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfCafica.Contexts.Administracion
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vistas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vistas()
        {
            this.AccionesVistas = new HashSet<AccionesVistas>();
            this.VistasGruposVistas = new HashSet<VistasGruposVistas>();
            this.VistasTablas = new HashSet<VistasTablas>();
            this.VistasFiltrosReportes = new HashSet<VistasFiltrosReportes>();
        }
    
        public long Id { get; set; }
        public string Nombre { get; set; }
        public string Parametros { get; set; }
        public string ImagenMenu { get; set; }
        public Nullable<byte> Orden { get; set; }
        public string UsuarioCreo { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModifico { get; set; }
        public Nullable<System.DateTime> FechaUltimaModificacion { get; set; }
        public string Tipo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccionesVistas> AccionesVistas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VistasGruposVistas> VistasGruposVistas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VistasTablas> VistasTablas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VistasFiltrosReportes> VistasFiltrosReportes { get; set; }
    }
}
