//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfCafica.Contexts
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AdminBD : DbContext
    {
        public AdminBD()
            : base(GetConnectionString())
        {
            this.Configuration.LazyLoadingEnabled = false;
    		this.Configuration.ProxyCreationEnabled = false;
        }
    	public static string GetConnectionString()
        {
            PasswordEncrypt encriptacion = new PasswordEncrypt();
            ValidarToken Token = new ValidarToken();
    
            //Obtiene el nombre usuario desde el token de la conexion
            string user = "root";
    
            //Obtiene el password a la bd 
            string password = "pwjr";
    
            string servidor;
            if (System.Diagnostics.Debugger.IsAttached)
                servidor ="10.10.1.72";
            else
                servidor ="10.10.1.170";
    
            // Server=localhost;Database={0};Uid=username;Pwd=password
            //var connString = ConfigurationManager.ConnectionStrings["UsuariosContext"].ConnectionString.ToString();
            string connString = "metadata=res://*/Contexts.AdminBD.csdl|res://*/Contexts.AdminBD.ssdl|res://*/Contexts.AdminBD.msl;provider=MySql.Data.MySqlClient;provider connection string=\"server={2};user id={0};password={1}\"";
    
            return String.Format(connString, user, password,servidor);
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    }
}
