//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfCafica.Contexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class BDEmpresas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BDEmpresas()
        {
            this.BDEmpresasRoles = new HashSet<BDEmpresasRoles>();
        }
    
        public long Id { get; set; }
        public string RazonSocial { get; set; }
        public string RFC { get; set; }
        public string Status { get; set; }
        public string ServidorIP { get; set; }
        public string UsuarioCreo { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioModifico { get; set; }
        public System.DateTime FechaUltimaModificacion { get; set; }
        public string UsuarioBD { get; set; }
        public string PasswordBD { get; set; }
        public string PuertoBD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BDEmpresasRoles> BDEmpresasRoles { get; set; }
    }
}
