//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfCafica.Contexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class GruposVistas
    {
        public long Id { get; set; }
        public string Nombre { get; set; }
        public long ModuloId { get; set; }
        public Nullable<sbyte> Orden { get; set; }
        public string UsuarioCreo { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioModifico { get; set; }
        public System.DateTime FechaUltimaModificacion { get; set; }
        public long SistemaId { get; set; }
    
        public virtual Modulos Modulos { get; set; }
        public virtual Sistemas Sistemas { get; set; }
    }
}
