//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfCafica.Contexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuariosRoles
    {
        public long Id { get; set; }
        public long UsuarioId { get; set; }
        public long RolId { get; set; }
        public string UsuarioCreo { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioModifico { get; set; }
        public System.DateTime FechaUltimaModificacion { get; set; }
    
        public virtual Roles Roles { get; set; }
    }
}
