//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfCafica.Contexts.Empresa
{
    using System;
    using System.Collections.Generic;
    
    public partial class  ComponentesFormulaDetalles
    {
        public long Id { get; set; }
        public long ComponenteId { get; set; }
        public Nullable<long> ComponenteFormulaId { get; set; }
        public long ComponenteHijoId { get; set; }
        public Nullable<double> Cantidad { get; set; }
        public long UnidadId { get; set; }
        public Nullable<double> CostoUnitario { get; set; }
        public Nullable<double> CostoTotal { get; set; }
        public string Estado { get; set; }
        public string UsuarioCreo { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModifico { get; set; }
        public Nullable<System.DateTime> FechaUltimaModificacion { get; set; }
    
        public virtual Componentes Componentes { get; set; }
        public virtual Componentes Componentes1 { get; set; }
        public virtual ComponentesFormula ComponentesFormula { get; set; }
        public virtual Unidades Unidades { get; set; }
    }
}
