//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfCafica.Contexts.Empresa
{
    using System;
    using System.Collections.Generic;
    
    public partial class  ComprasDocs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ComprasDocs()
        {
            this.ComprasDocsImpuestos = new HashSet<ComprasDocsImpuestos>();
            this.ComprasDocsRelaciones = new HashSet<ComprasDocsRelaciones>();
            this.ComprasDocsRelaciones1 = new HashSet<ComprasDocsRelaciones>();
            this.ComprasDocsDetalles = new HashSet<ComprasDocsDetalles>();
        }
    
        public long Id { get; set; }
        public string TipoDocumento { get; set; }
        public Nullable<long> SolicitanteId { get; set; }
        public Nullable<long> DepartamentoId { get; set; }
        public Nullable<long> AlmacenId { get; set; }
        public System.DateTime FechaDocumento { get; set; }
        public string Notas { get; set; }
        public string Estado { get; set; }
        public Nullable<long> ProveedorId { get; set; }
        public string Folio { get; set; }
        public string FolioProveedor { get; set; }
        public Nullable<long> MonedaId { get; set; }
        public Nullable<double> TipoCambio { get; set; }
        public string TipoDescuento { get; set; }
        public Nullable<double> DescuentoPorcentaje { get; set; }
        public Nullable<double> DescuentoImporte { get; set; }
        public Nullable<System.DateTime> FechaEntrega { get; set; }
        public Nullable<double> Subtotal { get; set; }
        public Nullable<double> Impuestos { get; set; }
        public Nullable<double> Retenciones { get; set; }
        public Nullable<double> Total { get; set; }
        public string ModuloOrigen { get; set; }
        public Nullable<long> CondicionesPagoId { get; set; }
        public Nullable<System.DateTime> FechaEnvio { get; set; }
        public string Enviado { get; set; }
        public string UsuarioCreo { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModifico { get; set; }
        public Nullable<System.DateTime> FechaUltimaModificacion { get; set; }
    
        public virtual Almacenes Almacenes { get; set; }
        public virtual CondicionesPago CondicionesPago { get; set; }
        public virtual Departamentos Departamentos { get; set; }
        public virtual Monedas Monedas { get; set; }
        public virtual Proveedores Proveedores { get; set; }
        public virtual Responsables Responsables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComprasDocsImpuestos> ComprasDocsImpuestos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComprasDocsRelaciones> ComprasDocsRelaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComprasDocsRelaciones> ComprasDocsRelaciones1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComprasDocsDetalles> ComprasDocsDetalles { get; set; }
    }
}
