//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfCafica.Contexts.Empresa
{
    using System;
    using System.Collections.Generic;
    
    public partial class  ComprasDocsImpuestos
    {
        public long Id { get; set; }
        public long ComprasDocsId { get; set; }
        public long ImpuestoId { get; set; }
        public double SubtotalCompra { get; set; }
        public Nullable<double> Otrosimpuestos { get; set; }
        public double Porcentaje { get; set; }
        public double Importe { get; set; }
        public string UsuarioCreo { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModifico { get; set; }
        public Nullable<System.DateTime> FechaUltimaModificacion { get; set; }
    
        public virtual ComprasDocs ComprasDocs { get; set; }
        public virtual Impuestos Impuestos { get; set; }
    }
}
