//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfCafica.Contexts.Empresa
{
    using System;
    using System.Collections.Generic;
    
    public partial class  ConceptosES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ConceptosES()
        {
            this.InventariosES = new HashSet<InventariosES>();
            this.InventariosESDetalles = new HashSet<InventariosESDetalles>();
        }
    
        public long Id { get; set; }
        public string Clave { get; set; }
        public string Nombre { get; set; }
        public string Predefinido { get; set; }
        public string Naturaleza { get; set; }
        public string FolioAutomatico { get; set; }
        public Nullable<long> TipoDocumentoId { get; set; }
        public string CostoAutomatico { get; set; }
        public string UsuarioCreo { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModifico { get; set; }
        public Nullable<System.DateTime> FechaUltimaModificacion { get; set; }
    
        public virtual TiposDocumentos TiposDocumentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventariosES> InventariosES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventariosESDetalles> InventariosESDetalles { get; set; }
    }
}
