//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfCafica.Contexts.Empresa
{
    using System;
    using System.Collections.Generic;
    
    public partial class  Impuestos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Impuestos()
        {
            this.ComponentesImpuestos = new HashSet<ComponentesImpuestos>();
            this.ComprasDocsImpuestos = new HashSet<ComprasDocsImpuestos>();
            this.ImpuestosGravados = new HashSet<ImpuestosGravados>();
            this.ImpuestosGravados1 = new HashSet<ImpuestosGravados>();
        }
    
        public long Id { get; set; }
        public string Nombre { get; set; }
        public string Naturaleza { get; set; }
        public string Tipo { get; set; }
        public string TipoCalculo { get; set; }
        public Nullable<double> Porcentaje { get; set; }
        public Nullable<double> CuotaUnidad { get; set; }
        public Nullable<long> UnidadId { get; set; }
        public string Predeterminado { get; set; }
        public string UsuarioCreo { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModifico { get; set; }
        public Nullable<System.DateTime> FechaUltimaModificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComponentesImpuestos> ComponentesImpuestos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComprasDocsImpuestos> ComprasDocsImpuestos { get; set; }
        public virtual Unidades Unidades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImpuestosGravados> ImpuestosGravados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImpuestosGravados> ImpuestosGravados1 { get; set; }
    }
}
