//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfCafica.Contexts.Empresa
{
    using System;
    using System.Collections.Generic;
    
    public partial class  InventariosFisicosDetalles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InventariosFisicosDetalles()
        {
            this.InventariosFisicosLotesSeries = new HashSet<InventariosFisicosLotesSeries>();
        }
    
        public long Id { get; set; }
        public long InventariosFisicosId { get; set; }
        public Nullable<long> InventariosESDetalleId { get; set; }
        public long ComponenteId { get; set; }
        public double ExistenciaFisica { get; set; }
        public Nullable<double> ExistenciaTeorica { get; set; }
        public Nullable<double> Diferencia { get; set; }
        public long ComponentesAlmacenesId { get; set; }
        public string UsuarioCreo { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModifico { get; set; }
        public Nullable<System.DateTime> FechaUltimaModificacion { get; set; }
    
        public virtual Componentes Componentes { get; set; }
        public virtual ComponentesAlmacenes ComponentesAlmacenes { get; set; }
        public virtual InventariosESDetalles InventariosESDetalles { get; set; }
        public virtual InventariosFisicos InventariosFisicos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventariosFisicosLotesSeries> InventariosFisicosLotesSeries { get; set; }
    }
}
