//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfCafica.Contexts.Empresa
{
    using System;
    using System.Collections.Generic;
    
    public partial class  InventariosES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InventariosES()
        {
            this.InventariosESDetalles = new HashSet<InventariosESDetalles>();
            this.InventariosFisicos = new HashSet<InventariosFisicos>();
            this.InventariosFisicos1 = new HashSet<InventariosFisicos>();
        }
    
        public long Id { get; set; }
        public long ConceptoId { get; set; }
        public long AlmacenId { get; set; }
        public string Folio { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Descripcion { get; set; }
        public string Naturaleza { get; set; }
        public double CostoTotal { get; set; }
        public string Cancelado { get; set; }
        public Nullable<long> SalidaTraspasoId { get; set; }
        public string FolioAutomatico { get; set; }
        public Nullable<long> TipoDocumentoId { get; set; }
        public string SalidaTraspasoAplicada { get; set; }
        public Nullable<long> AlmacenDestinoId { get; set; }
        public string ModuloOrigen { get; set; }
        public string UsuarioCreo { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModifico { get; set; }
        public Nullable<System.DateTime> FechaUltimaModificacion { get; set; }
    
        public virtual Almacenes Almacenes { get; set; }
        public virtual Almacenes Almacenes1 { get; set; }
        public virtual ConceptosES ConceptosES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventariosESDetalles> InventariosESDetalles { get; set; }
        public virtual TiposDocumentos TiposDocumentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventariosFisicos> InventariosFisicos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventariosFisicos> InventariosFisicos1 { get; set; }
    }
}
