//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfCafica.Contexts.Empresa
{
    using System;
    using System.Collections.Generic;
    
    public partial class  InventariosESDetalles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InventariosESDetalles()
        {
            this.InventariosESLotesSeries = new HashSet<InventariosESLotesSeries>();
            this.InventariosFisicosDetalles = new HashSet<InventariosFisicosDetalles>();
        }
    
        public long Id { get; set; }
        public long InventariosESId { get; set; }
        public long ConceptoId { get; set; }
        public string Naturaleza { get; set; }
        public long AlmacenId { get; set; }
        public long ComponenteId { get; set; }
        public System.DateTime Fecha { get; set; }
        public double Cantidad { get; set; }
        public double CostoUnitario { get; set; }
        public double CostoTotal { get; set; }
        public string MetodoCosteo { get; set; }
        public long ComponentesAlmacenesId { get; set; }
        public string TipoSeguimiento { get; set; }
        public string UsuarioCreo { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModifico { get; set; }
        public Nullable<System.DateTime> FechaUltimaModificacion { get; set; }
    
        public virtual Almacenes Almacenes { get; set; }
        public virtual Componentes Componentes { get; set; }
        public virtual ComponentesAlmacenes ComponentesAlmacenes { get; set; }
        public virtual ConceptosES ConceptosES { get; set; }
        public virtual InventariosES InventariosES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventariosESLotesSeries> InventariosESLotesSeries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventariosFisicosDetalles> InventariosFisicosDetalles { get; set; }
    }
}
