//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfCafica.Contexts.Empresa
{
    using System;
    using System.Collections.Generic;
    
    public partial class  LotesSeries
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LotesSeries()
        {
            this.ComprasDocsLotesSeries = new HashSet<ComprasDocsLotesSeries>();
            this.ExistenciasLotesSeries = new HashSet<ExistenciasLotesSeries>();
            this.InventariosESLotesSeries = new HashSet<InventariosESLotesSeries>();
            this.InventariosFisicosLotesSeries = new HashSet<InventariosFisicosLotesSeries>();
            this.ResguardosLotesSeries = new HashSet<ResguardosLotesSeries>();
        }
    
        public long Id { get; set; }
        public long ComponenteId { get; set; }
        public string Lote { get; set; }
        public Nullable<System.DateTime> FechaCaducidad { get; set; }
        public string NumeroSerie { get; set; }
        public string UsuarioCreo { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModifico { get; set; }
        public Nullable<System.DateTime> FechaUltimaModificacion { get; set; }
    
        public virtual Componentes Componentes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComprasDocsLotesSeries> ComprasDocsLotesSeries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExistenciasLotesSeries> ExistenciasLotesSeries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventariosESLotesSeries> InventariosESLotesSeries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventariosFisicosLotesSeries> InventariosFisicosLotesSeries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResguardosLotesSeries> ResguardosLotesSeries { get; set; }
    }
}
