//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfCafica.Contexts.Empresa
{
    using System;
    using System.Collections.Generic;
    
    public partial class  PremiosMonedero
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PremiosMonedero()
        {
            this.MovimientosMonederoDetalles = new HashSet<MovimientosMonederoDetalles>();
            this.SolicitudesCanjeMonederoDetalles = new HashSet<SolicitudesCanjeMonederoDetalles>();
            this.PremiosMonederoDetalles = new HashSet<PremiosMonederoDetalles>();
        }
    
        public long Id { get; set; }
        public string Nombre { get; set; }
        public Nullable<System.DateTime> FechaInicia { get; set; }
        public Nullable<System.DateTime> FechaTermina { get; set; }
        public int PuntosCanje { get; set; }
        public string ImagenBase64 { get; set; }
        public string UsuarioCreo { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModifico { get; set; }
        public Nullable<System.DateTime> FechaUltimaModificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovimientosMonederoDetalles> MovimientosMonederoDetalles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SolicitudesCanjeMonederoDetalles> SolicitudesCanjeMonederoDetalles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PremiosMonederoDetalles> PremiosMonederoDetalles { get; set; }
    }
}
