//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfCafica.Contexts.Empresa
{
    using System;
    using System.Collections.Generic;
    
    public partial class  PremiosMonederoDetalles
    {
        public long Id { get; set; }
        public long PremioMonederoId { get; set; }
        public long ComponenteId { get; set; }
        public double Cantidad { get; set; }
        public long UnidadId { get; set; }
        public double CantidadReal { get; set; }
        public long UnidadRealId { get; set; }
        public string UsuarioCreo { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModifico { get; set; }
        public Nullable<System.DateTime> FechaUltimaModificacion { get; set; }
    
        public virtual Componentes Componentes { get; set; }
        public virtual Unidades Unidades { get; set; }
        public virtual Unidades Unidades1 { get; set; }
        public virtual PremiosMonedero PremiosMonedero { get; set; }
    }
}
