//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfCafica.Contexts.Empresa
{
    using System;
    using System.Collections.Generic;
    
    public partial class  Proveedores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proveedores()
        {
            this.ComprasDocs = new HashSet<ComprasDocs>();
            this.ProveedoresDirecciones = new HashSet<ProveedoresDirecciones>();
            this.ProveedoresContactos = new HashSet<ProveedoresContactos>();
        }
    
        public long Id { get; set; }
        public string Nombre { get; set; }
        public string NombreComercial { get; set; }
        public string RFC { get; set; }
        public Nullable<long> GruposProveedoresId { get; set; }
        public Nullable<long> GiroId { get; set; }
        public string Email { get; set; }
        public string Telefono1 { get; set; }
        public string Telefono2 { get; set; }
        public string Activo { get; set; }
        public Nullable<long> MonedaId { get; set; }
        public Nullable<long> CondicionesPagoId { get; set; }
        public Nullable<double> LimiteCredito { get; set; }
        public string Celular { get; set; }
        public string Notas { get; set; }
        public string UsuarioCreo { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModifico { get; set; }
        public Nullable<System.DateTime> FechaUltimaModificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComprasDocs> ComprasDocs { get; set; }
        public virtual CondicionesPago CondicionesPago { get; set; }
        public virtual Giros Giros { get; set; }
        public virtual GrupoProveedores GrupoProveedores { get; set; }
        public virtual Monedas Monedas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProveedoresDirecciones> ProveedoresDirecciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProveedoresContactos> ProveedoresContactos { get; set; }
    }
}
