//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfCafica.Contexts.Empresa
{
    using System;
    using System.Collections.Generic;
    
    public partial class  ResguardosDetalles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ResguardosDetalles()
        {
            this.ResguardosLotesSeries = new HashSet<ResguardosLotesSeries>();
        }
    
        public long Id { get; set; }
        public long ResguardoId { get; set; }
        public string TipoDocumento { get; set; }
        public Nullable<long> ResponsableId { get; set; }
        public long ComponenteId { get; set; }
        public double Cantidad { get; set; }
        public long ComponentesAlmacenesId { get; set; }
        public string Notas { get; set; }
        public Nullable<long> AlmacenId { get; set; }
        public string Cancelado { get; set; }
        public string UsuarioCreo { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModifico { get; set; }
        public Nullable<System.DateTime> FechaUltimaModificacion { get; set; }
    
        public virtual Almacenes Almacenes { get; set; }
        public virtual Componentes Componentes { get; set; }
        public virtual ComponentesAlmacenes ComponentesAlmacenes { get; set; }
        public virtual Resguardos Resguardos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResguardosLotesSeries> ResguardosLotesSeries { get; set; }
    }
}
