//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfCafica.Contexts.Empresa
{
    using System;
    using System.Collections.Generic;
    
    public partial class  SociosMonedero
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SociosMonedero()
        {
            this.MovimientosMonedero = new HashSet<MovimientosMonedero>();
        }
    
        public long Id { get; set; }
        public string Nombre { get; set; }
        public string Servidor { get; set; }
        public Nullable<double> FactorMontoCompra { get; set; }
        public Nullable<int> FactorPuntos { get; set; }
        public Nullable<int> AntiguedadTicket { get; set; }
        public string GrupoSocio { get; set; }
        public string UsuarioCreo { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModifico { get; set; }
        public Nullable<System.DateTime> FechaUltimaModificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovimientosMonedero> MovimientosMonedero { get; set; }
    }
}
